### ISSUE TITLE
May I port this to Forge?

### ISSUE THREAD

**Issue by AzureDoom** [RelativityMC/unsafe-world-random-access-detector#1]
**Is your feature request related to a problem? Please describe.**
Not a problem, just would like to expend this mod as I found it highly useful for Fabric and would love a tool like this for Forge! 

**Describe the solution you'd like**
If you are ok with it, I'd like to do a Forge port, which can be done via a Fork if you wish, linking back this this or PRing into an branch for you to release.

**Describe alternatives you've considered**
Nothing really like this is on Forge.

**Additional context**
I know the license allows me to just fork and do this, but I feel it's respect to ask permission for from you. Any porting would of course keep your credits if you don't to host it under your page.

**Comment by ishland** [comment]
I've ported this to forge (5b70ca27e8fd91b1f53b4a8af67aa34222e0c2a9) and tested this change working on forge versions  `1.19-41.1.0`, `1.19.1-42.0.9`, `1.19.2-43.2.8`, `1.19.3-44.1.23`, `1.19.4-45.0.46` with only this mod. 

The curseforge page is still under review: https://legacy.curseforge.com/minecraft/mc-mods/uwrad-forge
The forge version is already published on Modrinth: https://modrinth.com/mod/uwrad/version/1.1.0+forge

**Comment by AzureDoom** [comment]
Thank you very much!
